# Generated by Django 6.0.4 on 2026-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_borrowrecord_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='fine_paid',
            field=models.BooleanField(default=False),
        ),
    ]
